### ISSUE TITLE
veo solo dos comiters 

### ISSUE THREAD

**Issue by javierajorge** [generobruno/CryptoCalculator#5]
La implementacion es de 64 bits, practicamente no usan la convencion de llamadas. 
sugiero usar 32bits para que puedan explotar el concepto. 
Como falta alguien que confirme. Esa persona se encargará de hacer los arreglos para que funcione con 32 bits

**Comment by generobruno** [comment]
Buenos días profesor.
La implementación en 32 bits esta en la carpeta "C/" ya que usamos libcurl
en lenguaje C y una fifo para comunicar el proceso de 64 bits que hace uso
de esta librería (c/src/requests
<https://github.com/generobruno/CryptoCalculator/blob/master/c/src/requests/request.c>)
con el proceso de 32 bits que hace la convención de llamadas a ASM (
c/src/driver
<https://github.com/generobruno/CryptoCalculator/blob/master/c/src/driver/driver.c>
).
Todos ayudamos con la implementación pero la persona que no realizó commits
no está acostumbrada aún a usar git. Quedan un par de cosas que se pueden
mejorar en esa implementación, además de agregar documentación, así que
podemos hacer que utilice git y github en eso si le parece.

**Comment by javierajorge** [comment]
Me parece barbaro !  es indispensable e importante que todos aporten confirmando cambios, documentacion etc... 
vean estos issues y ayuden al cumpa que falta a que arregle estas cosas en su proyecto seguro que tienen problemas similares. 

https://github.com/FrancoNB/TP2_SC_2023/issues
